{% set name = "scisoftpy" %}
{% set version = "2.37.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d685ca4a1e66dbee17767e8d213e3aa739462c8b638183b5d487159e451931cc

build:
  number: 1
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - h5py  # depends on numpy
    - pillow
    - six
    - tifffile
    - pycbf  # [py3k]
    - packaging  # [py >= 40]
    - numpy

test:
  imports:
    - scisoftpy

about:
  home: https://gerrit.diamond.ac.uk/admin/repos/scisoft/scisoft-core
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Dawn Python Extensions

extra:
  recipe-maintainers:
    - jacobfilik
    - PeterC-DLS
    - jacobfilik
