{% set name = "scisoftpy" %}
{% set version = "2.37.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9ed77f45536a73dfdc00a976f09333f13d2a0c3a6cc18631b94ccd47b7518a49

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - python
    - pip
    - setuptools

  run:
    - python
    - h5py  # depends on numpy
    - pillow
    - six
    - tifffile
    - pycbf  # [py3k]
    - packaging  # [py >= 40]
    - numpy <2

test:
  imports:
    - scisoftpy

about:
  home: https://gerrit.diamond.ac.uk/admin/repos/scisoft/scisoft-core
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Dawn Python Extensions

extra:
  recipe-maintainers:
    - jacobfilik
    - PeterC-DLS
    - jacobfilik
