{% set name = "scisoftpy" %}
{% set version = "2.23.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 930e27231b1154ae79e55c5fdd8ae044a424dbec7cc2cd24d6130d8dce1a4e0d

build:
  number: 0
  script: '{{ PYTHON }} -m pip install . -vv '

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - h5py
    - numpy
    - pillow
    - py4j
    - python
    - six
    - subprocess32  # [unix and py2k]

test:
  imports:
    - scisoftpy

about:
  home: https://gerrit.diamond.ac.uk/admin/repos/scisoft/scisoft-core
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Dawn Python Extensions

extra:
  recipe-maintainers:
    - PeterC-DLS
    - tschoonj
